// Code generated by dbus-codegen-go DO NOT EDIT.
package main

import (
	"context"
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceComHiveioVmManager               = "com.hiveio.vm.Manager"
	InterfaceOrgFreedesktopDBusIntrospectable = "org.freedesktop.DBus.Introspectable"
)

// NewComHiveioVmManager creates and allocates com.hiveio.vm.Manager.
func NewComHiveioVmManager(object dbus.BusObject) *ComHiveioVmManager {
	return &ComHiveioVmManager{object}
}

// ComHiveioVmManager implements com.hiveio.vm.Manager D-Bus interface.
type ComHiveioVmManager struct {
	object dbus.BusObject
}

// CheckHostForMigration calls com.hiveio.vm.Manager.CheckHostForMigration method.
func (o *ComHiveioVmManager) CheckHostForMigration(ctx context.Context, guestName string, cpuxml string) (result bool, err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmManager+".CheckHostForMigration", 0, guestName, cpuxml).Store(&result)
	return
}

// RecoverGuest calls com.hiveio.vm.Manager.RecoverGuest method.
func (o *ComHiveioVmManager) RecoverGuest(ctx context.Context, guestName string, reason string) (err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmManager+".RecoverGuest", 0, guestName, reason).Store()
	return
}

// RecoverUservolume calls com.hiveio.vm.Manager.RecoverUservolume method.
func (o *ComHiveioVmManager) RecoverUservolume(ctx context.Context, guestName string, username string) (err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmManager+".RecoverUservolume", 0, guestName, username).Store()
	return
}

// NewOrgFreedesktopDBusIntrospectable creates and allocates org.freedesktop.DBus.Introspectable.
func NewOrgFreedesktopDBusIntrospectable(object dbus.BusObject) *OrgFreedesktopDBusIntrospectable {
	return &OrgFreedesktopDBusIntrospectable{object}
}

// OrgFreedesktopDBusIntrospectable implements org.freedesktop.DBus.Introspectable D-Bus interface.
type OrgFreedesktopDBusIntrospectable struct {
	object dbus.BusObject
}

// Introspect calls org.freedesktop.DBus.Introspectable.Introspect method.
func (o *OrgFreedesktopDBusIntrospectable) Introspect(ctx context.Context) (out string, err error) {
	err = o.object.CallWithContext(ctx, InterfaceOrgFreedesktopDBusIntrospectable+".Introspect", 0).Store(&out)
	return
}
