// Code generated by dbus-codegen-go DO NOT EDIT.
package main

import (
	"context"
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceComHiveioVmmanager               = "com.hiveio.vmmanager"
	InterfaceOrgFreedesktopDBusIntrospectable = "org.freedesktop.DBus.Introspectable"
)

// NewComHiveioVmmanager creates and allocates com.hiveio.vmmanager.
func NewComHiveioVmmanager(object dbus.BusObject) *ComHiveioVmmanager {
	return &ComHiveioVmmanager{object}
}

// ComHiveioVmmanager implements com.hiveio.vmmanager D-Bus interface.
type ComHiveioVmmanager struct {
	object dbus.BusObject
}

// CheckHostForMigration calls com.hiveio.vmmanager.CheckHostForMigration method.
func (o *ComHiveioVmmanager) CheckHostForMigration(ctx context.Context, guestName string, cpuxml string) (result bool, err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmmanager+".CheckHostForMigration", 0, guestName, cpuxml).Store(&result)
	return
}

// RecoverGuest calls com.hiveio.vmmanager.RecoverGuest method.
func (o *ComHiveioVmmanager) RecoverGuest(ctx context.Context, guestName string, reason string) (err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmmanager+".RecoverGuest", 0, guestName, reason).Store()
	return
}

// RecoverUservolume calls com.hiveio.vmmanager.RecoverUservolume method.
func (o *ComHiveioVmmanager) RecoverUservolume(ctx context.Context, guestName string, username string) (err error) {
	err = o.object.CallWithContext(ctx, InterfaceComHiveioVmmanager+".RecoverUservolume", 0, guestName, username).Store()
	return
}

// NewOrgFreedesktopDBusIntrospectable creates and allocates org.freedesktop.DBus.Introspectable.
func NewOrgFreedesktopDBusIntrospectable(object dbus.BusObject) *OrgFreedesktopDBusIntrospectable {
	return &OrgFreedesktopDBusIntrospectable{object}
}

// OrgFreedesktopDBusIntrospectable implements org.freedesktop.DBus.Introspectable D-Bus interface.
type OrgFreedesktopDBusIntrospectable struct {
	object dbus.BusObject
}

// Introspect calls org.freedesktop.DBus.Introspectable.Introspect method.
func (o *OrgFreedesktopDBusIntrospectable) Introspect(ctx context.Context) (out string, err error) {
	err = o.object.CallWithContext(ctx, InterfaceOrgFreedesktopDBusIntrospectable+".Introspect", 0).Store(&out)
	return
}
